server:
  port: 8191
spring:
  cloud:
    config:
      server:
	      #can be any server or hosted store. In this case I am using git.
        git:
          uri: https://github.com/vaibhavg12/demo-config-store
          search-paths:
           #to pick up all sub folders sending with word "service"
		       - '*service'